version: '3.5'

services:
  # mqtt-server
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - ${ROOT_PATH}/Data/mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  # zigbee2mqtt
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ${ROOT_PATH}/Data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      TZ: "${TIMEZONE}"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0