version: '3.5'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ${ROOT_PATH}/Data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "${Z2M_WEB_PORT}:8080"
    environment:
      TZ: "${TIMEZONE}"
    devices:
      - ${Z2M__DEVICE_PATH}:/dev/ttyUSB0
    networks:
      - "smart-home-control"

networks:
  smart-home-control:
    external: true
    name: "smart-home-control"