version: '3.5'

services:
  # mqtt-server
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - ${ROOT_PATH}/Data/mosquitto/conf:/mosquitto/config
      - ${ROOT_PATH}/Data/mosquitto/data:/mosquitto/data
      - ${ROOT_PATH}/Data/mosquitto/log:/mosquitto/log
    ports:
      - "${MQTT_PORT}:1883"
      - "${MQTT_TLS_PORT}:9001"
    environment:
      TZ: ${TIMEZONE}
  #  labels:
  #    com.centurylinklabs.watchtower.enable: "true"

  # zigbee2mqtt
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ${ROOT_PATH}/Data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "${Z2M_WEB_PORT}:8080"
    environment:
      TZ: "${TIMEZONE}"
    devices:
      - ${Z2M__DEVICE_PATH}:/dev/ttyUSB0
